### ISSUE TITLE
fix naming strategy,code 

### ISSUE THREAD

**Issue by mzarsaw** [naeimrezaeian/ACT-ADMIN#20]
the name of the component does not match with other components. please fix it.
![image](https://github.com/naeimrezaeian/ACT-ADMIN/assets/6144486/3c06f614-0758-4f8a-a163-644433f1e728)
also, these codes shouldn't be there. please move them to a new Vuex state or directly into the component. need a good reason to have a new Vuex state
![image](https://github.com/naeimrezaeian/ACT-ADMIN/assets/6144486/9a6853ee-a3ba-41f9-b342-bc77766d7e86)
![image](https://github.com/naeimrezaeian/ACT-ADMIN/assets/6144486/2bc0f3e6-c2ed-4bd9-ae7c-f2002261eda1)

**Comment by AryanSMD** [comment]
@mzarsaw done
