### ISSUE TITLE
add upload file for manual check subtests

### ISSUE THREAD

**Issue by mzarsaw** [naeimrezaeian/ACT-ADMIN#30]
in the below form, some of the subtests need manual checks so the user will upload the student's answers as a PDF file. so we need to put an upload button for those subtests that need manual check
![image](https://github.com/naeimrezaeian/ACT-ADMIN/assets/6144486/18179698-3f7c-45a4-bcbe-947c2ec6d8df)

so add an upload button here for example
![image](https://github.com/naeimrezaeian/ACT-ADMIN/assets/6144486/9811253c-b76c-4f03-ac3c-1d1dff84d3c3)
question how we know a subtest needs a manual check. in getUserResultMatrix response to new fields added
![image](https://github.com/naeimrezaeian/ACT-ADMIN/assets/6144486/f7f9575a-d5b2-4d1b-a325-b832698d4b11)
IsManualcheck and UserAnswerFileId,
IsManualCheck determines if the subtest needs a manual check or not. and upload the file as you did previously. and call this API
POST /api/admin/branchexams/UploadUserExam
body:{
"UserSubtestId":"id of user subtest",
"UserAnswserFileId":"the uploaded file id"
}
also, add functionality to remove or change file and view file

**Comment by AryanSMD** [comment]
@mzarsaw done #36
