### ISSUE TITLE
issue in showing Subtest Time by new timepicker

### ISSUE THREAD

**Issue by mzarsaw** [naeimrezaeian/ACT-ADMIN#49]
when a user tries to edit a subtest, subtest time will not load and please test full functionality add/edit the subtest and make sure it works fine
![image](https://github.com/naeimrezaeian/ACT-ADMIN/assets/6144486/3964b297-7a5c-4ed1-a962-38dbbeb53ed8)

**Comment by AryanSMD** [comment]
@mzarsaw done
