### ISSUE TITLE
add data validation to all forms

### ISSUE THREAD

**Issue by mzarsaw** [naeimrezaeian/ACT-ADMIN#60]
This API is for checking if an email exists
![image](https://github.com/naeimrezaeian/ACT-ADMIN/assets/6144486/34130271-53a3-4043-956c-942c587cbc20)
response is 
{ email="test@test.co", Exists = true }
true on exists means email is exists and not valid otherwise false means it is valid

**Comment by AryanSMD** [comment]
@mzarsaw done #31
